---
apiVersion: policy.linkerd.io/v1alpha1
kind: ClientPolicyBinding
metadata:
  name: books
spec:
  policyRefs:
    - group: policy.linkerd.io
      kind: HTTPClientPolicy
      namespace: booksapp
      name: books
  podSelector:
    matchLabels:
      app: books

