apiVersion: policy.linkerd.io/v1alpha1
kind: ClientPolicy
metadata:
  name: books
spec:
  targetRef:
    name: books
    kind: Service
    namespace: booksapp
  failureClassification:
    statuses:
      - "401"
      - "402"
      - "503"
      - "500-599"
  filters:
    - type: Timeout
      timeout: 1s
