apiVersion: policy.linkerd.io/v1alpha1
kind: ClientPolicyBinding
metadata:
  name: authors
  namespace: booksapp
spec:
  policyRefs:
    - group: policy.linkerd.io
      kind: HTTPClientPolicy
      namespace: booksapp
      name: authors-get
    - group: policy.linkerd.io
      kind: HTTPClientPolicy
      namespace: booksapp
      name: authors-modify
    - group: policy.linkerd.io
      kind: HTTPClientPolicy
      namespace: booksapp
      name: books-get
    - group: policy.linkerd.io
      kind: HTTPClientPolicy
      namespace: booksapp
      name: books-delete
  podSelector:
    matchExpressions:
      - { key: app, operator: NotIn, values: [] }