apiVersion: policy.linkerd.io/v1alpha1
kind: HTTPClientPolicy
metadata:
  name: authors-get
spec:
  targetRef:
    name: authors-get-route
    kind: HTTPRoute
    group: policy.linkerd.io
    namespace: booksapp
    port: service
  failureClassification:
    statuses:
      - "401"
      - "402"
      - "500-599"
  filters:
    - type: Timeout
      timeout: 500ms
