---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clientpolicies.policy.linkerd.io
spec:
  group: policy.linkerd.io
  names:
    kind: ClientPolicy
    listKind: ClientPolicyList
    plural: clientpolicies
    singular: clientpolicy
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
