---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpclientpolicies.policy.linkerd.io
spec:
  group: policy.linkerd.io
  names:
    kind: HTTPClientPolicy
    listKind: HTTPClientPolicyList
    plural: httpclientpolicies
    singular: httpclientpolicy
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
